### ISSUE TITLE
mvn packed 7.9.1 fail

### ISSUE THREAD

**Issue by bogiahuy** [duydo/elasticsearch-analysis-vietnamese#87]
D:\test\vn-nlp-libraries\nlp-parent\elasticsearch-analysis-vietnamese\src\test\java\org\elasticsearch\index\analysis\VietnameseAnalysisTest.java:[10,41] error: cannot find symbol

Please help me

**Comment by Wizard2069** [comment]
Just move your elasticsearch-analysis-vietnamese folder to your root folder (in your case D:\test), after that this should work well with elastic v7.5.1
